HOSTNAME = "120.76.202.170"
PORT = "3306"
DATABASE = "test"
USERNAME = "LWH"
PASSWORD = "123456"
DB_URI = f"mysql+pymysql://{USERNAME}:{PASSWORD}@{HOSTNAME}:{PORT}/{DATABASE}"
SQLALCHEMY_DATABASE_URI = DB_URI

UPLOAD_FOLDER = "./upload"