"""empty message

Revision ID: 96dd0e5aa001
Revises: ff547c488587
Create Date: 2023-02-01 13:53:08.273575

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '96dd0e5aa001'
down_revision = 'ff547c488587'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game_exchange_code', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Diamond', sa.Integer(), nullable=False))
        batch_op.create_unique_constraint(None, ['code'])
        batch_op.drop_column('id')
        batch_op.drop_column('Giamond')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game_exchange_code', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Giamond', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('Diamond')

    # ### end Alembic commands ###
