"""empty message

Revision ID: ff547c488587
Revises: 
Create Date: 2023-01-31 21:47:22.009373

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff547c488587'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('announcements',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('announcement', sa.String(length=99), nullable=False),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('download_record',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=15), nullable=False),
    sa.Column('is_download', sa.Enum('是', '否'), nullable=False),
    sa.Column('file_md5', sa.String(length=99), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('game_exchange_code',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=99), nullable=False),
    sa.Column('GoldCoin', sa.Integer(), nullable=False),
    sa.Column('Giamond', sa.Integer(), nullable=False),
    sa.Column('is_use', sa.Enum('是', '否'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_info',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=15), nullable=False),
    sa.Column('password', sa.String(length=15), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_info')
    op.drop_table('game_exchange_code')
    op.drop_table('download_record')
    op.drop_table('announcements')
    # ### end Alembic commands ###
